name: Release

on:
    push:
        tags:
            # Run when a tag (e.g. "vX.X.X") is pushed.
            - "v*"

permissions:
    # Required to create/write the release archive.
    contents: write

jobs:
    release:
        runs-on: macos-latest

        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Setup Rust
              uses: dtolnay/rust-toolchain@stable

            - name: Build
              run: |
                  # Strip leading (e.g. "refs/tags/vX.X.X") path segments.
                  VERSION="${GITHUB_REF##*/}"
                  ARCHIVE="envcmd_${VERSION}_darwin_arm64"

                  mkdir -p dist && cargo build --release --target aarch64-apple-darwin

                  # -c: Create an archive.
                  # -z: Use GZIP compression.
                  # -f: Output archive name.
                  # -C: Change into source directory.
                  tar -czf "dist/${ARCHIVE}.tar.gz" -C target/aarch64-apple-darwin/release envcmd
                  echo "ARCHIVE=${ARCHIVE}.tar.gz" >> $GITHUB_ENV

            - name: Generate Checksum
              run: |
                  FILE="dist/${ARCHIVE}"
                  echo "[CHECKSUM]" && shasum -a 256 "$FILE"

            - name: Create Release
              uses: softprops/action-gh-release@v2
              with:
                  files: |
                      dist/*.tar.gz
